version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nestjs_backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: yarn start:dev

volumes:
  mongo_data:
